#!/bin/sh

# promote staging branch to heroku staging server

if [ -z "$1" ]
then
	echo "must specify name for release branch"
	exit;
fi

git push staging $1:master
heroku rake db:migrate --remote staging